### ISSUE TITLE
Any plans to release new version?

### ISSUE THREAD

**Issue by serrj-sv** [jcchikikomori/GmsCoreHuawei#25]
Hi,  
Do you have any plans about releasing new version with latest patches from upstream?
Thanks!

**Comment by jcchikikomori** [comment]
> Hi, Do you have any plans about releasing new version with latest patches from upstream? Thanks!

I have plans however, I am currently working full-time on a private company so I don't have much time to work on personal projects like this.

Anyway, thank you for following up.

**Comment by jcchikikomori** [comment]
@serrj-sv Currently working on it! Stay tuned

![image](https://user-images.githubusercontent.com/4709030/149626379-6af04ad3-2652-44b3-810f-980a34cb113e.png)

**Comment by serrj-sv** [comment]
Hi @jcchikikomori thanks for new release!
Please also check latest release from upstream, looks like they added some workarounds for Huawei phones as well!
