### ISSUE TITLE
Is there any updates or releases soon?

### ISSUE THREAD

**Issue by Mohammed1520** [jcchikikomori/GmsCoreHuawei#36]
Sorry for annoying but is there any upcoming updates for microg for Huawei?

**Comment by jcchikikomori** [comment]
> Sorry for annoying but is there any upcoming updates for microg for Huawei?

My apologies. There are upcoming developments, however, due to busy schedule and microG already implemented device spoofing for HUAWEI, I might not continue updating this fork, or pull from upstream then check their implementation.
